
name: ci-test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  db-test:
    name: Test Database
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: 123
        ports:
          - 5432:5432

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create DB
        run: make createdb

      - name: Test
        run: make test